spring:
  application:
    name: game-marketplace-backend

  datasource:
    url: jdbc:postgresql://54.89.226.119:5432/postgres
    username: postgres
    password: root@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: codeoxi.com@gmail.com
    password: bcdi oqkq sltg wapq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

server:
  port: 9999

jwt:
  secret-key: $2a$12$5pIKMCnwfMmotzq3GnVbMOt6dnw5qH8vBG4Lt4vyWgF.NsRH1mRqy


payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: Z7MCGZGD
    secretKey: 28LF7UIUL9Z9K0DT8EWMWWCALOF08F63
    returnUri: http://localhost:9999/api/transactions/p/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other

cloudinary:
  cloud_name: dx66jgmlq
  api_key: 512594293551369
  api_secret: lhFCO61qmidjvmhmQSQN3jN69ds

