spring:
  application:
    name: game-marketplace-backend
    api-prefix: /api/v1

  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
    username: postgres.liepbbvffjosyozrjpwx
    password: $2a$12$xXRBsG5lh0MhcV8WOStR4u5OfPQ1DOFVa5y.CCMnFLT2BECZ0Wiqq
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#  security:
#    user:
#      name: user
#      password: password

  mail:
    host: smtp.gmail.com
    port: 587
    username: cskh.divineshop@gmail.com
    password: vpycwonbktedhjsg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

server:
  port: 9999

jwt:
  secret-key: $2a$12$5pIKMCnwfMmotzq3GnVbMOt6dnw5qH8vBG4Lt4vyWgF.NsRH1mRqy


payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: Z7MCGZGD
    secretKey: 28LF7UIUL9Z9K0DT8EWMWWCALOF08F63
    returnUrl: http://localhost:9999/api/v1/payment/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other
